# Generated by Django 2.2 on 2020-03-05 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('age', models.IntegerField(null=True)),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=80, null=True)),
                ('classe', models.CharField(choices=[('TC1', 'TC1'), ('TC2', 'TC2'), ('DIC1', 'DIC1'), ('DIC2', 'DIC2'), ('DIC3', 'DIC3')], max_length=50, null=True)),
                ('genie', models.CharField(choices=[('GIT', 'Génie Informatique et Télécommunications'), ('Génie Civil', 'Génie Civil'), ('Génie Electromécanique', 'Génie Electro-Mécanique'), ('Tronc Commun', 'Tronc Commun')], max_length=100, null=True)),
                ('photo_profile', models.ImageField(blank=True, default='user-default.png', null=True, upload_to='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aime', models.IntegerField(default=0)),
                ('question', models.TextField(max_length=200)),
                ('date_question', models.DateTimeField(auto_now_add=True)),
                ('eleve_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ged_app.Eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0)),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
                ('reponse', models.TextField(max_length=500, null=True)),
                ('el', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ged_app.Eleve')),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ged_app.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='media/')),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
                ('classe_doc', models.CharField(choices=[('TC1', 'TC1'), ('TC2', 'TC2'), ('DIC1', 'DIC1'), ('DIC2', 'DIC2'), ('DIC3', 'DIC3')], max_length=50, null=True)),
                ('genie_doc', models.CharField(choices=[('GIT', 'Génie Informatique et Télécommunications'), ('Génie Civil', 'Génie Civil'), ('Génie Electromécanique', 'Génie Electro-Mécanique'), ('Tronc Commun', 'Tronc Commun')], max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ged_app.Eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commentaire', models.DateTimeField(auto_now_add=True, null=True)),
                ('choc', models.IntegerField(default=0)),
                ('signaler', models.IntegerField(default=0)),
                ('contenu', models.TextField(max_length=1000, null=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ged_app.Eleve')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ged_app.Document')),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repliques', to='ged_app.Commentaire')),
            ],
        ),
    ]
